### ISSUE TITLE
dactyl build crash

### ISSUE THREAD

**Issue by maybeTomorrow** [ripple/dactyl#61]
Traceback (most recent call last):
  File "/usr/local/bin/dactyl_build", line 8, in <module>
    sys.exit(dispatch_main())
  File "/usr/local/lib/python3.9/site-packages/dactyl/dactyl_build.py", line 620, in dispatch_main
    main(cli.cli_args, config)
  File "/usr/local/lib/python3.9/site-packages/dactyl/dactyl_build.py", line 575, in main
    builder = DactylBuilder(target, config, mode)
  File "/usr/local/lib/python3.9/site-packages/dactyl/dactyl_build.py", line 79, in __init__
    self.setup_html_env() # sets self.html_env
  File "/usr/local/lib/python3.9/site-packages/dactyl/dactyl_build.py", line 293, in setup_html_env
    loaderset = [jinja2.PackageLoader(__name__)]
  File "/usr/local/lib/python3.9/site-packages/jinja2/loaders.py", line 309, in __init__
    raise ValueError(
ValueError: The 'dactyl.dactyl_build' package was not installed in a way that PackageLoader understands.

**Comment by mDuo13** [comment]
I've seen this one and it appears to be an incompatibility with Jinja 3.x. For now, you can `pip install Jinja2==2.11.3` to work around the error. 

I'm still investigating if there's a way for Dactyl to be compatible with older Python versions and newer Jinja versions simultaneously.

**Comment by mDuo13** [comment]
Fixed in [v0.14.3](https://github.com/ripple/dactyl/releases/tag/v0.14.3).
